sequenceDiagram
    participant H as home directory
    participant W as working copy
    participant L as local repo
    participant R as remote repo
    W->>W: chezmoi edit
    W->>H: chezmoi apply
    W->>H: chezmoi edit --apply
    W->>H: chezmoi edit --watch