# generated by AI with nothing to start from. Not bad but a bit depressing.

import curses
import random
import time


def draw_firework(stdscr, y, x, char, color_pair=0):
    stdscr.addstr(y, x, char, curses.color_pair(color_pair))
    stdscr.refresh()

def animate_firework(stdscr, max_x):
    max_y = 10
    y = 10 - 1
    x = random.randint(0, max_x - 1)
    while y > 0:
        draw_firework(stdscr, y, x, '*', 1)
        time.sleep(0.01)
        draw_firework(stdscr, y, x, ' ')
        y -= 1

    explosion_patterns = [
        [(0, 0), (-1, 0), (1, 0), (0, -1), (0, 1)],
        [(0, 0), (-1, -1), (1, 1), (-1, 1), (1, -1)],
        [(0, 0), (-2, 0), (2, 0), (0, -2), (0, 2)]
    ]
    pattern = random.choice(explosion_patterns)
    color_pair = random.randint(1, 3)

    for _ in range(10):
        for dy, dx in pattern:
            if 0 <= y + dy < max_y and 0 <= x + dx < max_x:
                draw_firework(stdscr, y + dy, x + dx, '*', color_pair)
        time.sleep(0.1)
        for dy, dx in pattern:
            if 0 <= y + dy < max_y and 0 <= x + dx < max_x:
                draw_firework(stdscr, y + dy, x + dx, ' ')

def draw_text(stdscr, text, y, x):
    for i, line in enumerate(text.splitlines()):
        stdscr.addstr(y + i, x, line)
    stdscr.refresh()

def main(stdscr):
    curses.curs_set(0)
    curses.start_color()
    curses.init_pair(1, curses.COLOR_RED, curses.COLOR_BLACK)
    curses.init_pair(2, curses.COLOR_GREEN, curses.COLOR_BLACK)
    curses.init_pair(3, curses.COLOR_YELLOW, curses.COLOR_BLACK)
    stdscr.nodelay(1)
    stdscr.timeout(100)

    max_y, max_x = stdscr.getmaxyx()

    while True:
        animate_firework(stdscr, max_x)
        if stdscr.getch() != -1:
            break

    text_2025 = """
  ____   ___   ___   ____
 |___ \\ / _ \\ / _ \\ |___ \\
   __) | | | | | | |  __) |
  / __/| |_| | |_| | / __/
 |_____|\\___/ \\___(_)_____|
"""

    draw_text(stdscr, text_2025, max_y // 2 - 3, max_x // 2 - 20)
    time.sleep(1.0)
    stdscr.getch()

curses.wrapper(main)
