sequenceDiagram
    participant H as home directory
    participant W as working copy
    participant L as local repo
    participant R as remote repo
    R->>W: chezmoi init <repo>
    W-->>H: chezmoi diff
    W->>H: chezmoi apply
    W->>W: chezmoi edit <file>
    W->>W: chezmoi merge <file>
    R->>H: chezmoi update