name: Pylint and Pip Audit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install pylint pip-audit textual

      - name: Run pylint
        run: |
          pylint -E $(git ls-files '*.py') # Adjusted to check all Python files

      - name: Run pip-audit
        run: pip-audit